<?php
pll_register_string('category', 'category', 'category', true);
pll_register_string('category', 'infomation', 'category', true);
pll_register_string('category', 'service', 'category', true);
pll_register_string('category', 'recentnews', 'category', true);
pll_register_string('category', 'imagegallery', 'category', true);
pll_register_string('category', 'populartags', 'category', true);
pll_register_string('post', 'nothingmatched', 'post', true);
pll_register_string('post', 'searchingcanhelp', 'post', true);
pll_register_string('post', 'nothingfound', 'post', true);

pll_register_string('post', 'keyword', 'post', true);
pll_register_string('post', 'search', 'post', true);
pll_register_string('post', 'close', 'post', true);
pll_register_string('post', 'infocontact', 'post', true);
pll_register_string('post', 'support', 'post', true);
pll_register_string('post', 'taxcode', 'post', true);
pll_register_string('post', 'description', 'post', true);
pll_register_string('post', 'client', 'post', true);
pll_register_string('post', 'document', 'post', true);
pll_register_string('account', 'member', 'account', true);
pll_register_string('account', 'login', 'account', true);
pll_register_string('account', 'welcome', 'account', true);
pll_register_string('account', 'welcome', 'account', true);
pll_register_string('account', 'signout', 'account', true);
pll_register_string('email', 'email', 'email', true);
pll_register_string('email', 'consultant', 'email', true);
pll_register_string('email', 'fullname', 'email', true);
pll_register_string('email', 'phone', 'email', true);
pll_register_string('email', 'note', 'email', true);
pll_register_string('address', 'addresscorp1', 'address', true);
pll_register_string('address', 'addresscorp2', 'address', true);
pll_register_string('address', 'addresscorp3', 'address', true);
pll_register_string('address', 'titleofffice', 'address', true);
pll_register_string('form', 'success', 'form', true);
pll_register_string('form', 'comment', 'form', true);
pll_register_string('form', 'submit', 'form', true);
pll_register_string('form', 'review', 'form', true);
pll_register_string('form', 'post', 'form', true);
pll_register_string('form', 'thanksyourcomment', 'form', true);
/*button*/
pll_register_string('home', 'lawyer', 'home', true);
pll_register_string('button', 'bt-contactus', 'button', true);
pll_register_string('button', 'needhelp', 'button', true);
pll_register_string('button', 'makeappoint', 'button', true);
pll_register_string('button', 'readmore', 'button', true);
pll_register_string('footer', 'services', 'footer', true);
pll_register_string('footer', 'news', 'footer', true);
?>